"""Entry point for a single rolling-window job (training + forecasting + metrics).

Called by the sbatch script run_financial_window.sh:
    python financial/run_window.py --config-name <name> --window-idx <int>

The config name is the key generated by prepare_windows.py (e.g.
nvda_ts_a1.50_obsstd0.05_train30d_fc2d). All paths are derived from it:
    financial/data/prepared/{config_name}/config.yaml       (config snapshot)
    financial/data/prepared/{config_name}/window_{idx}.pkl  (window data)
    financial/results/{config_name}/window_{idx}/metrics.json
    financial/results/{config_name}/window_{idx}/model.eqx
    financial/results/{config_name}/window_{idx}/forecast_samples.pkl
"""

import sys
import argparse
import json
import pickle
import yaml
import random as pyrandom
import numpy as np
import jax.random as jrandom
import equinox as eqx
from pathlib import Path

# Repo root on path
sys.path.insert(0, str(Path(__file__).parent.parent))

from financial.data.windows import load_window
from financial.training.train_window import train_window, build_output_paths
from financial.forecasting.predict import generate_forecast_samples
from financial.evaluation.metrics import compute_all_metrics, DENSE_COVERAGE_LEVELS

RESULTS_DIR = Path(__file__).parent / 'results'
PREPARED_DIR = Path(__file__).parent / 'data' / 'prepared'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config-name', required=True,
                        help='Config name as generated by prepare_windows.py')
    parser.add_argument('--window-idx', type=int, required=True)
    parser.add_argument('--result-name', default=None,
                        help='Results directory name (default: same as config-name). '
                             'Pass a versioned name (e.g. config_v2) to avoid '
                             'clobbering previous results.')
    args = parser.parse_args()

    config_name = args.config_name
    window_idx = args.window_idx
    result_name = args.result_name if args.result_name else config_name

    # Load config from the snapshot saved by prepare_windows.py.
    # Jobs never read the live financial/configs/ files.
    config_path = PREPARED_DIR / config_name / 'config.yaml'
    if not config_path.exists():
        raise FileNotFoundError(
            f"Config snapshot not found: {config_path}\n"
            f"Run prepare_windows.py first."
        )
    with open(config_path) as f:
        cfg = yaml.safe_load(f)
    cfg['_config_name'] = config_name

    # -------------------------------------------------------------------------
    # Skip if already done
    # -------------------------------------------------------------------------
    result_dir = RESULTS_DIR / result_name / f"window_{window_idx:04d}"
    metrics_path = result_dir / 'metrics.json'
    if metrics_path.exists():
        print(f"Window {window_idx:04d} already evaluated, skipping.")
        return

    # -------------------------------------------------------------------------
    # Load window
    # -------------------------------------------------------------------------
    window_path = PREPARED_DIR / config_name / f"window_{window_idx:04d}.pkl"
    if not window_path.exists():
        raise FileNotFoundError(
            f"Window file not found: {window_path}\n"
            f"Run prepare_windows.py first."
        )
    window = load_window(window_path)

    print(f"Window {window_idx:04d}: "
          f"{len(window['train_times'])} train obs, "
          f"{len(window['forecast_times'])} forecast obs")

    # -------------------------------------------------------------------------
    # Train
    # -------------------------------------------------------------------------
    training_seed = pyrandom.randint(0, 2 ** 31)
    model, training_metrics = train_window(cfg, window, RESULTS_DIR, training_seed=training_seed)

    # Save model
    result_dir.mkdir(parents=True, exist_ok=True)
    model_path = result_dir / 'model.eqx'
    eqx.tree_serialise_leaves(str(model_path), model)
    print(f"Saved model to {model_path}")

    # -------------------------------------------------------------------------
    # Forecast
    # -------------------------------------------------------------------------
    eval_cfg = cfg.get('evaluation', {})
    n_forecast_samples = eval_cfg.get('n_forecast_samples', 500)
    quantile_levels = eval_cfg.get('quantile_levels', DENSE_COVERAGE_LEVELS)
    path_weight_threshold = eval_cfg.get('path_weight_threshold', 20.0)

    n_latent_steps = cfg['training']['n_latent_steps']
    use_posterior_for_forecast = eval_cfg.get('use_posterior_for_forecast', False)
    key = jrandom.key(training_seed)
    forecast_samples = generate_forecast_samples(
        model, window, n_forecast_samples, key,
        n_latent_steps=n_latent_steps,
        use_posterior_for_forecast=use_posterior_for_forecast,
    )
    # forecast_samples: (K, H, D)

    # Save forecast samples
    samples_path = result_dir / 'forecast_samples.pkl'
    with open(samples_path, 'wb') as f:
        pickle.dump(forecast_samples, f)

    # -------------------------------------------------------------------------
    # Metrics
    # -------------------------------------------------------------------------
    forecast_obs = window['forecast_returns']  # (H, D)
    if forecast_obs.ndim == 1:
        forecast_obs = forecast_obs[:, None]
    if forecast_samples.ndim == 2:
        forecast_samples = forecast_samples[:, :, None]

    metrics = compute_all_metrics(
        forecast_samples, forecast_obs, quantile_levels,
        path_weight_threshold=path_weight_threshold,
    )

    # Shared window metadata attached to both metrics files.
    def _attach_metadata(m):
        m['window_idx'] = window_idx
        m['n_train_obs'] = int(len(window['train_times']))
        m['n_forecast_obs'] = int(len(window['forecast_times']))
        m['window_start_day'] = float(window['window_start_day'])
        m['time_scale'] = float(window.get('time_scale', 1.0))
        m['forecast_times'] = window['forecast_times'].tolist()
        m['forecast_obs'] = forecast_obs.tolist()
        m['norm_mu'] = window['norm_mu'].tolist()
        m['norm_sigma'] = window['norm_sigma'].tolist()

    _attach_metadata(metrics)

    # Save standard metrics (no observation noise)
    with open(metrics_path, 'w') as f:
        json.dump(metrics, f, indent=2)

    # -------------------------------------------------------------------------
    # Obs-noise metrics: add N(0, obs_std^2) to each forecast sample before
    # recomputing.  This gives the predictive distribution for y = x + eps
    # rather than just x, which is the statistically correct comparison against
    # the observed returns.
    # -------------------------------------------------------------------------
    obs_std = cfg['data']['obs_std']
    rng = np.random.default_rng(training_seed)
    noisy_samples = forecast_samples + rng.normal(0.0, obs_std, forecast_samples.shape).astype(
        forecast_samples.dtype
    )
    metrics_noisy = compute_all_metrics(
        noisy_samples, forecast_obs, quantile_levels,
        path_weight_threshold=path_weight_threshold,
    )
    _attach_metadata(metrics_noisy)

    noisy_metrics_path = result_dir / 'metrics_obs_noise.json'
    with open(noisy_metrics_path, 'w') as f:
        json.dump(metrics_noisy, f, indent=2)

    print(f"Window {window_idx:04d} complete — "
          f"CRPS={metrics['mean_crps']:.4f} "
          f"(+obs_noise: {metrics_noisy['mean_crps']:.4f}), "
          f"ES={metrics['mean_energy_score']:.4f}")


if __name__ == '__main__':
    main()
